[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'php82Extensions.pdo_pgsql', 'php82Extensions.pgsql', 'php82Extensions.pdo_mysql', 'php82Extensions.pdo', 'php82Extensions.openssl', 'php82Extensions.mbstring', 'php82Extensions.curl']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'php artisan view:clear',
    'php artisan route:clear'
]

[start]
cmd = 'php artisan config:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
